name: Full Build
permissions:
  contents: write
on:
  push:
    branches:
      - main
jobs:
  bb-full-build:
    runs-on: ubuntu-latest
    concurrency:
      group: full-build-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 20

      - uses: DeLaGuardo/setup-clojure@11.0
        with:
          cli: 1.11.1.1347
          bb: 1.3.179
          clj-kondo: 2023.04.14

      - id: cache-maven
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2
            ~/.gitlibs
          key: ${{ runner.os }}-${{ hashFiles('deps.edn') }}

      - name: bb full-build
        run: |
          bb full-build

      - name: Upload Clojure error logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: error-logs
          path: /tmp/clojure-*.edn

      - uses: JamesIves/github-pages-deploy-action@v4.4.2
        with:
          folder: target/resources/public
